# Generated by Django 5.2.6 on 2025-09-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoPublico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('andamento', 'Em andamento'), ('aprovado', 'Aprovado'), ('cancelado', 'Cancelado')], default='andamento', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='prestadorservico',
            name='user',
        ),
        migrations.RemoveField(
            model_name='solicitacaoservico',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='AgendamentoServico',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='PrestadorServico',
        ),
        migrations.DeleteModel(
            name='SolicitacaoServico',
        ),
    ]
