# Generated by Django 5.2.6 on 2025-10-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_agendamentopublico_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentopublico',
            name='notificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agendamentopublico',
            name='status',
            field=models.CharField(choices=[('andamento', 'Em andamento'), ('aprovado', 'Aprovado'), ('cancelado', 'Cancelado')], default='andamento', max_length=10),
        ),
    ]
