# Generated by Django 5.1.2 on 2025-10-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_agendamentopublico_notificado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentopublico',
            name='notificado',
        ),
        migrations.AlterField(
            model_name='agendamentopublico',
            name='status',
            field=models.CharField(choices=[('andamento', 'Em andamento'), ('aprovado', 'Aprovado'), ('cancelado', 'Cancelado'), ('notificado', 'Notificado')], default='andamento', max_length=15),
        ),
    ]
